CREATE TYPE user_role AS ENUM ('ROLE_PM', 'ROLE_USER', 'ROLE_ADMIN');

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    roles user_role[] NOT NULL
);